import { CtaSection } from "@/components/CtaSection";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Vaelo",
  description: "Terms of service for the Vaelo financial analysis platform.",
};

export default function TermsPage() {
  const currentDate = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <main>
      <section className="bg-white py-20 border-b border-ledger-line">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

          <div className="mb-12 border-b border-ledger-line pb-8">
            <h1 className="text-4xl font-serif text-ink tracking-tight mb-4">Terms of Service</h1>
            <p className="text-slate text-sm font-mono uppercase tracking-wider">Effective Date: {currentDate}</p>
          </div>

          <div className="prose prose-slate prose-headings:font-serif prose-headings:text-ink prose-headings:font-medium prose-p:text-slate prose-a:text-corporate-blue max-w-none space-y-8">

            <div>
              <p className="text-lg leading-relaxed mb-6">
                These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Vaelo platform (&quot;Service&quot;), operated by Vaelo (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). By accessing or using the Service, you agree to be bound by these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">1. Eligibility &amp; Account</h2>
              <p>
                The Service is designed for Chartered Accountants (CAs) and financial professionals operating in India. You must be at least 18 years old and legally authorized to enter into a binding agreement. When you create an account, you agree to provide accurate information and keep it current. You are solely responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">2. Description of Service</h2>
              <p>
                Vaelo provides a financial analysis workspace that enables CAs to generate deterministic, formula-driven reports for their clients across three core modules: Credit Monitoring Arrangement (CMA), Financial Health Snapshot, and Feasibility Analysis. Clients added to the workspace may receive permission-scoped access to view reports generated for them.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">3. Pricing &amp; Payments</h2>
              <p>
                Access to Vaelo requires a one-time setup fee and an ongoing monthly subscription, the specifics of which are published on our Pricing page. We reserve the right to update pricing with 30 days&apos; prior written notice. Failure to pay outstanding invoices may result in suspension of your account.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">4. Your Data &amp; Intellectual Property</h2>
              <p>
                You retain full ownership of all financial data, reports, and outputs generated through the Service. We claim no intellectual property rights over your content. By uploading data, you grant us a limited, non-exclusive license solely to process and store it for the purpose of delivering the Service to you. Our handling of personal and financial data is governed by our Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">5. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 space-y-2 mt-4">
                <li>Use the Service for any unlawful purpose or in violation of applicable regulations.</li>
                <li>Attempt to reverse-engineer, decompile, or disassemble any part of the platform.</li>
                <li>Share your account credentials with unauthorized third parties.</li>
                <li>Upload data that you do not have the legal right to process.</li>
                <li>Interfere with or disrupt the integrity or performance of the Service.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">6. Disclaimers</h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as available.&quot; Vaelo provides computational tools to assist your professional judgment — it does not provide financial, legal, or tax advice. All reports generated by the platform are based on the inputs you provide and the deterministic models applied to them. You are solely responsible for verifying the accuracy of outputs before presenting them to clients, regulators, or other third parties.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">7. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, Vaelo shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or business opportunities arising from your use of the Service. Our total cumulative liability shall not exceed the amount you have paid to us in the twelve (12) months preceding the claim.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">8. Termination</h2>
              <p>
                You may close your account at any time by contacting us. We may suspend or terminate your access if you breach these Terms, fail to pay outstanding invoices, or engage in activity that harms the Service or other users. Upon termination, your data will be handled in accordance with our Privacy Policy and data retention schedule.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">9. Changes to These Terms</h2>
              <p>
                We may revise these Terms from time to time. We will notify you of material changes by email or by posting a prominent notice on the platform at least 30 days before the changes take effect. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms.
              </p>
            </div>

            <div>
              <h2 className="text-2xl mt-10 mb-4">10. Governing Law &amp; Disputes</h2>
              <p>
                These Terms are governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Ahmedabad, Gujarat.
              </p>
            </div>

            <div className="pt-8 mt-12 border-t border-ledger-line">
              <h2 className="text-2xl mb-4">11. Contact</h2>
              <p>
                If you have any questions about these Terms, please contact us at:
              </p>
              <p className="mt-4 font-mono font-medium text-corporate-blue">
                vaelo.team@gmail.com
              </p>
            </div>

          </div>
        </div>
      </section>
      <CtaSection />
    </main>
  );
}
